libjanus_rtpbroadcast.c
We need bitrate statistics for average, min, max, current?
=> Publish: RTP inbound stats

README.md, libjanus_rtpbroadcast.c
Implement the administrative communication channel between plugin code and `cm-janus`
@kris-lab @njam
=> Janus -> CM-Janus pathway

conf/janus.plugin.cm.rtpbroadcast.cfg.sample, libjanus_rtpbroadcast.c
TODO
- dump RTP packets into filename of streamChannelKey?
- send EVENT up to `cm-janus` via transport!
```
{
"name": "archive-ready",
"filename": "path-to-the-file"
}
```
=> Recording: auto recording and event notification

README.md, conf/janus.plugin.cm.rtpbroadcast.cfg.sample, libjanus_rtpbroadcast.c
Part of #14 
As discussed there is need to store queue of pushed event about `archive-ready`, `thumbnail-ready`! We have to make sure that any `cm-janus` ACK-ed this notification!
=> Persistence layer for admin notification (super-user)

test/README.md, test/tester.py
Add test scripts I use to the README
=> Sample test scripts

libjanus_rtpbroadcast.c
> maybe investigate SRTP integration
=> Publish: RTP inbound IP filtering/authentication 

libjanus_rtpbroadcast.c
Seems not the case automatically
=> Ensuring mountpoints are destroyed when session is closed

libjanus_rtpbroadcast.c
@kris-lab please review and merge this as well.
=> Fixes to #28

conf/janus.plugin.cm.rtpbroadcast.cfg.sample, libjanus_rtpbroadcast.c, test/tester.py
=> Switching threshold

libjanus_rtpbroadcast.c
The "switch" event doesn't consider new logic of:
- stream switching with `cm_rtpbcast_pick_source`?
- `src->listeners` which are moved to the `source` from `mounpoint`?
@landswellsong could you verify?
=> "switch" event bug

Vagrantfile
@kris-lab please review this, pretty small change. Might be a dealbreaker for new deployments.
=> Vagrant fixes

libjanus_rtpbroadcast.c, test/tester.py
If possible we should detect keyframe in the stream and use this logic during streams switching. Technically the switch of stream would be scheduled and actual switching would happen only if "key frame" appears in the new stream.
part of #5
=> RTP: detect keyframe in the stream

README.md, conf/janus.plugin.cm.rtpbroadcast.cfg.sample, libjanus_rtpbroadcast.c
In a configurable time interval? 10 seconds?
=> Send "stream-definition" regularly to client

README.md, libjanus_rtpbroadcast.c
- return on `create` action
- store in `jobFile`
=> Add "uid" for mountpoint instance

README.md, libjanus_rtpbroadcast.c
=> Add "createdAt" field to thumbnail job

README.md, libjanus_rtpbroadcast.c
This is testing implementation which allows for initial benchmarking.
TODO:
=> Add UDP relay gateway + UDP client + scaling logic

README.md, Vagrantfile, libjanus_rtpbroadcast.c, test/tester.py
This should allow to upgrade plugin-handle session to be super user. 
Super user events:
- mountpoint create
- mountpoint destroy
- all mountpoint list every defined time period
TODO:
=> Add super user support

test/tester.py
@kris-lab please review and merge. This would allow us to test and reproduce the crash from `tester.py` without relying on browser and timings.
=> Multi instance tester

libjanus_rtpbroadcast.c, test/tester.py
@kris-lab please have a look. Also needs testing.
=> Simplify udp socket

libjanus_rtpbroadcast.c, test/tester.py
Reverts cargomedia/janus-gateway-rtpbroadcast#70
=> Revert "Simplify udp socket"

test/tester.py
=> Detach command and move towards endpoint-based REST API

libjanus_rtpbroadcast.c
Part of https://github.com/cargomedia/puppet-cargomedia/issues/1409
---
=> Segfaults during stream switching

libjanus_rtpbroadcast.c
=> Segfaults during stream switching - take 3

libjanus_rtpbroadcast.c
=> Make multi-thread safe for sessions, mp and sources

libjanus_rtpbroadcast.c
Reverts cargomedia/janus-gateway-rtpbroadcast#117
=> Revert "Mountpoint is not cleaned up properly"

README.md, conf/janus.plugin.cm.rtpbroadcast.cfg.sample, libjanus_rtpbroadcast.c
Reverts cargomedia/janus-gateway-rtpbroadcast#106
=> Revert "Adjust "thumbnails recorder" to be resistant for packets lost"

libjanus_rtpbroadcast.c
Reverts cargomedia/janus-gateway-rtpbroadcast#110
=> Revert "Detect VP8 frame fragmented across RTP packets"

libjanus_rtpbroadcast.c
Reverts cargomedia/janus-gateway-rtpbroadcast#115
=> Revert "Make multi-thread safe for sessions, mp and sources - take 2"

libjanus_rtpbroadcast.c
Reverts cargomedia/janus-gateway-rtpbroadcast#113
=> Revert "Segfaults during stream switching - take 3"

libjanus_rtpbroadcast.c
Reverts cargomedia/janus-gateway-rtpbroadcast#108
=> Revert "Segfaults during stream switching"

libjanus_rtpbroadcast.c
Reverts cargomedia/janus-gateway-rtpbroadcast#114
=> Revert "Make multi-thread safe for sessions, mp and sources"

libjanus_rtpbroadcast.c
Reverts cargomedia/janus-gateway-rtpbroadcast#112
=> Revert "Segfaults during stream switching - take 2"

libjanus_rtpbroadcast.c
Part of https://github.com/cargomedia/puppet-packages/pull/1579
=> Fix job_temp_path
