conf/janus.plugin.cm.rtpbroadcast.cfg.sample
libjanus_rtpbroadcast.c

TODO:
- investigate best option:
- RTP server and FFMPEG client with JPEG output
- dump RTP packets to the file and notify `cm-janus` to convert into JPEG using Gstreamer?
- try to detect KEYFRAME
- send EVENT up to cm-janus
```
{
"name": "thumbnail-ready",
"filename": "path-to-the-file"
}
```

Recording: auto thumbnailer + event notification

---

libjanus_rtpbroadcast.c

If we send `{recorder: true}` it is not recognised as boolean. We had to send `{recorder: '1'}`
@vogdb fyi

Create-event: Recorder field must be send as string '0' otherwise fails to be boolean

---

conf/janus.plugin.cm.rtpbroadcast.cfg.sample
libjanus_rtpbroadcast.c

`snprintf` doesn't play nice with positional arguments when some of them are omitted. Replacing all pattern substitution with Glib one. Low prio right now.

Use Glib formatting

---

conf/janus.plugin.cm.rtpbroadcast.cfg.sample

There are some issues
Used config
```
[general]
; Port range for automatic port generation
; minport = 8000
; maxport = 9000
; NOTE: all paths should exist beforehead
; Path for job JSONs
job_path=/var/lib/janus/jobs
; prinf pattern for job filenames (.json is auto)
; Short usage, the following gets substituted:
; #{time}     is timestamp (guint64)
; #{rand}     is random integer (guin32)
; #{md5}      is md5 of (timestamp + plugin name + random integer)
; #{plugin}   is plugin name ("janus.plugin.cm.rtpbroadcast")
job_pattern = "job-#{md5}"
; Path for recording and thumbnailing
archive_path=/var/lib/janus/recordings
; printf pattern for recordings filenames
; Short usage, the following gets substituted:
; #{id}       is streamChannelKey (string)
; #{time}     is timestamp (guint64)
; …
```

Bugs overview

---

libjanus_rtpbroadcast.c

```
Creating new session: 3359450195
Creating new handle in session 3359450195: 3723401204
[<string>] Recording audio started
[<string>] Recording video started
[<string>] New audio stream! (ssrc=906131872)
[<string>] New video stream! (ssrc=1563571768)
[<string>] New audio stream! (ssrc=3063090431)
[<string>] New video stream! (ssrc=1891070994)
[2650383836] Creating ICE agent (ICE Full mode, controlling)
(process:15154): libnice-WARNING **: Could not find component 1 in stream 2
(process:15154): libnice-WARNING **: Could not find component 2 in stream 2
[2650383836] The DTLS handshake has been completed
WebRTC media is now available
[WSS-0x1ac0100] Destroying WebSocket client
Timeout expired for session 3359450195...
Detaching handle from JANUS CM video plugin
No WebRTC media anymore …
```

Stream switching: Cannot destroy mountpoint, close session, shutdown Janus

---

libjanus_rtpbroadcast.c

Currently there is auto source switching based on REMBs  and RTP average bitrate. I would suggest to implement new event called `switch-source` which would allow to disable auto switching and stick to specific source?
Request:
```js
{
id: "streamChannelKey",
streamSource: <int>
...
}
```

Stream switching: allow to set source manually

---

README.md
libjanus_rtpbroadcast.c

I would suggest to extend `stream-definition` with more `session` info (user REMB, autoswitch etc):
```json
{
"id": "1",
"index": 2,
"audioport": 8190,
"videoport": 8551,
"stats": {
"min": 3941003.7472473467,
"max": 3971467.7421128997,
"cur": 3960143.3665105496,
"avg": 3957183.5333239716
},
"frame": {
"width": 1280,
"height": 720,
"fps": 25,
"key-distance": 30
},
"session": {
"webrtc-active": 0,
"autoswitch-enabled": 1,
"remb-avg": 558964
}
}
```

Extend stream definition

---

libjanus_rtpbroadcast.c

@kris-lab @njam I'll summarise my findings about the bug here. The bug is caused by the following:
1. Session `A` creates a mountpoint `M`.
2. Session `B` initiates `watch-udp` to this mountpoint, this spawns 3 instances of `cm_rtpbcast_udp_relay_gateway` into a `GArray`. Each of `M`'s sources add `B` to their `listeners` list. 
3. **Here is the error** compared to what I have in `watch`, `B` has no way of knowing which sources to it is connected.
4. `B` disconnects, times out or whatever. Since (3) it does not remove itself from `listeners` anywhere.
5. `A` disconnects, times out or whatever. It goes through `listeners` of each sources for the mountpoint it streams, then it tries to send shutdown signals to the session `A` which has already quit. This is timing dependent because `B` is …

Refactor UDP client inner structures

---

libjanus_rtpbroadcast.c

It seems that `cm_rtpbcast_pick_source` is not picking proper `source` if the `array` contains unsorted average `(guint64)src->stats.avg`
@landswellsong wdyt?

Verify cm_rtpbcast_pick_source is working properly

---

conf/janus.plugin.cm.rtpbroadcast.cfg.sample
libjanus_rtpbroadcast.c
test/udp_relay_log2csv

Part of #64 and https://github.com/cargomedia/janus-gateway-rtpbroadcast/pull/65
TODO:

Improve WebRTC/UDP relay switching mode

---

libjanus_rtpbroadcast.c

Currently we sometimes create recordings of 8 bytes, if there is no data.
In that case we should make sure to not create a job file.

Don't create job file if there is no data

---

README.md
conf/janus.plugin.cm.rtpbroadcast.cfg.sample
libjanus_rtpbroadcast.c
test/tester.py

When looking at the client code I noticed again this asymmetry with retrieving the janus server configuration. The hostname is configured *in the client*, while the port number is retrieved *from the server* (with the mountpoint *create* call).
I think even if we hardcode it, all this information should come from a single place. The server itself should know how it can be reached (because there's no ICE). Maybe we can configure the "public rtp hostname" in the plugin configuration, and return it with the port?
Wdyt? Do you see a good way how it can be accomplished?

Return public RTP host on "mountpoint creation"

---

README.md
conf/janus.plugin.cm.rtpbroadcast.cfg.sample
libjanus_rtpbroadcast.c

Currently we send the session info every `session_info_update_time` seconds, and it is averaged over `source_avg_time`. I would suggest to combine the two into 1 value.
Then on the client we can just store the average whenever we receive it, and average again over those averages if desired.
cc @zazabe

Single config value for session info interval

---

libjanus_rtpbroadcast.c

Last message is always "Timeout expired for session":
```
[Thu Apr 14 13:53:47 2016] [hvu39xGoT9Aoir4MqtbI0w__] New audio stream! (ssrc=4259405333)
[Thu Apr 14 13:53:47 2016] [hvu39xGoT9Aoir4MqtbI0w__] New audio stream! (ssrc=212122636)
[Thu Apr 14 13:53:47 2016] [hvu39xGoT9Aoir4MqtbI0w__] New video stream! (ssrc=3188504535)
[Thu Apr 14 13:53:50 2016] Creating new handle in session 1616202850: 3328866235
[Thu Apr 14 13:53:50 2016] [3328866235] Creating ICE agent (ICE Full mode, controlling)
[Thu Apr 14 13:53:50 2016] [3328866235] The DTLS handshake has been completed
[Thu Apr 14 13:53:50 2016] WebRTC media is now available
[Thu Apr 14 13:54:10 2016] [WSS-0xfc6000] Destroying WebSocket client
[Thu Apr 14 13:54:11 2016] Timeout expired for session 2681868537...
````

rtpbroadcast dies on development VM

---

libjanus_rtpbroadcast.c

"packet-loss" value "1" is reported over WebSocket, so probably a problem in the rtpbroadcast plugin.

janus rtpbroadcast: check packet loss metric

---

README.md
conf/janus.plugin.cm.rtpbroadcast.cfg.sample
libjanus_rtpbroadcast.c

Part of https://github.com/cargomedia/sk/issues/2891
Because we can trust the client to do the correct timing and calculation.
This is also what I experienced during my tests.
Reference: https://tools.ietf.org/html/draft-alvestrand-rtcweb-congestion-03
```
; Watcher REMB averageing interval, seconds
; remb_avg_interval = 3
; Switching interval, seconds
; switching_delay = 1
```
@kris-lab wdyt?
cc @zazabe

Remove averaging and delay of auto-switch

---

libjanus_rtpbroadcast.c

As investigated with @zazabe there are some bugs in the `cm_rtpbcast_pick_source`.
Also see related: https://github.com/cargomedia/janus-gateway-rtpbroadcast/issues/91

Fixes for pick-up the right stream based on REMB

---

libjanus_rtpbroadcast.c

Seems to not working properly. It shows packets lost even if e.g. `iperf` reports 0.

Investigate wrong "packet-loss-count" calculation

---

libjanus_rtpbroadcast.c

Packet loss count not resetting correctly?

---

README.md
libjanus_rtpbroadcast.c

On the client side, it would be nice to receive the same data than `mountpoint-info` instead of `{autoswitch: 0, current: {...}, next: {...}}`.

"switchSource" response with same data than "mountpoint-info" event

---

libjanus_rtpbroadcast.c

Part of https://github.com/cargomedia/puppet-cargomedia/issues/1203
Part of https://github.com/cargomedia/puppet-cargomedia/issues/1115
(copying myself)
> - keyframe is splitted into many RTP packets: there might be a case if keyframe is made of e.g. 5 RTP packets and we detect 1st RTP packet as proper keyframe. However if following packets are corrupted (by UDP loss) there will be problem on the decode level. We should make sure that marking frame as keyframe is done only if all releated data (packets) are valid.
- not enough data arrived - freezing problem - in general we should give a track of data flow and avoid storing data (thumbs/records) if we detect UDP loss. Currently it is possible due to the metrics we collect.

Make sure we do not create "thumbnails" while RTP packets lost occurred

---

libjanus_rtpbroadcast.c

Core dump:
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/bin/janus -o -C /opt/janus-cluster/janus/etc/janus/janus.cfg -L /opt/janus'.
Program terminated with signal 11, Segmentation fault.
#0  0x00000000004351fc in janus_plugin_relay_rtp ()
(gdb) where
#0  0x00000000004351fc in janus_plugin_relay_rtp ()
#1  0x00007fd1696b9d51 in ?? () from /opt/janus-cluster/janus/usr/lib/janus/plugins.enabled/libjanus_rtpbroadcast.so
#2  0x00007fd16fec266d in g_list_foreach () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fd1696b9329 in ?? () from /opt/janus-cluster/janus/usr/lib/janus/plugins.enabled/libjanus_rtpbroadcast.so
#4  0x00007fd16fee7f45 in ?? () from …
```

Segfaults during stream switching - take 2

---

libjanus_rtpbroadcast.c

Version [0.0.24](https://github.com/cargomedia/janus-gateway-rtpbroadcast/releases/tag/v0.0.24) crashes with
```
Core was generated by `/usr/bin/janus -o -C /opt/janus-cluster/janus/etc/janus/janus.cfg -L /opt/janus'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007f81c7aab1b6 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
(gdb) where
#0  0x00007f81c7aab1b6 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007f81c7aab419 in g_mutex_lock () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f81c7a4628a in g_async_queue_push () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f81c1263383 in ?? () from /opt/janus-cluster/janus/usr/lib/janus/plugins.enabled/libjanus_rtpbroadcast.so
#4  0x00007f81c7a6c66d in g_list_foreach () from …
```

Make multi-thread safe for sessions, mp and sources - take 2

---

README.md
conf/janus.plugin.cm.rtpbroadcast.cfg.sample
libjanus_rtpbroadcast.c

Depends on https://github.com/cargomedia/janus-gateway-rtpbroadcast/issues/110
As reported https://github.com/cargomedia/puppet-cargomedia/issues/1347 there is possibility that thumbnail recorder is not resistant for packets lost and finally dumps RTP packets and job file even if data is corrupted. 
For records the logic has been introduced https://github.com/cargomedia/janus-gateway-rtpbroadcast/pull/102

Adjust "thumbnails recorder" to be resistant for packets lost

---

libjanus_rtpbroadcast.c

There are frozen mountpoints left after WS disconnects unexpected and session is removed.

Mountpoint is not cleaned up properly
